RabbitMQ Healthcheck Contribution
codingjoe/django-health-check pull request #197
Opened 2018-07-12 02:39 UTC by IgooorGP

This pull request contains the following implementations:

-  A class to perform the healthcheck of a RabbitMQ service;
- Tests for the RabbitMQ Healthchecker;
- An updated README.rst with the instructions on how to configure the RabbitMQ healthchecker.

2018-07-12 09:46 UTC, codingjoe reviewed
Hi @IgooorGP great work! Really appreciate the effort. Especially about including tests!

I do have some comments. Please also make sure to add documentation.

2018-07-12 09:46 UTC, codingjoe commented on .gitignore
> +
Please add editor specific ignores to you global git ignore. Not to a repository.

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/apps.py
> +        plugin_dir.register(RabbitMQHealthCheck)
missing newline

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +
Please drop trailing blank line

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +
Please drop trailing blank line

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +        if broker_url is None:
I have the feeling this drives complexity. I'd rather have only one approach on how to configure this correctly.

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +        return broker_url
This can return `None`

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +    def __get_broker_url(self):
Why use a dunder method here?

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +            conn = pika.BlockingConnection(pika.URLParameters(broker_url))
I am not so sure about pika. Most people will use celery and it's `amqplib` fork.

2018-07-12 09:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +            self.add_error(ServiceUnavailable("Unable to connect to RabbitMQ: Connection refused."), e)
You can also just use `raise ServiceUnavailable("your message") from e`

2018-07-12 09:46 UTC, codingjoe commented on requirements-dev.txt
> +pika
yet another dependency...

2018-07-12 09:46 UTC, codingjoe commented on setup.cfg
> +max-line-length = 119
Unrelated change.

2018-07-12 09:46 UTC, codingjoe commented on tests/test_rabbitmq.py
> +    unittest.main()
Kudos for writing tests. I really appreciate it. But we use pytest as a test runner.

2018-07-18 00:33 UTC, ipeternella commented on .gitignore
> +
Hello there @codingjoe! I have removed these files to a global git ignore. Sorry for this mistake.

2018-07-18 00:33 UTC, ipeternella commented on health_check/contrib/rabbitmq/apps.py
> +        plugin_dir.register(RabbitMQHealthCheck)
Done!

2018-07-18 00:33 UTC, ipeternella commented on health_check/contrib/rabbitmq/backends.py
> +
Done!

2018-07-18 00:33 UTC, ipeternella commented on health_check/contrib/rabbitmq/backends.py
> +
I have removed this method due to the mentioned complexity of the configuration.

2018-07-18 00:33 UTC, ipeternella commented on health_check/contrib/rabbitmq/backends.py
> +        if broker_url is None:
I have removed this method due to the mentioned complexity. Right now, the RabbitMQ healthchecker only looks for a BROKER_URL variable on django settings dict.

2018-07-18 00:34 UTC, ipeternella commented on health_check/contrib/rabbitmq/backends.py
> +            conn = pika.BlockingConnection(pika.URLParameters(broker_url))
I have removed pika from the dependencies. Instead of it, I use Kombu which is a dependency of the Celery package and therefore comes together with Celery! Kombu uses pyamqp by default according to its docs http://docs.celeryproject.org/projects/kombu/en/latest/userguide/connections.html

2018-07-18 00:34 UTC, ipeternella commented on requirements-dev.txt
> +pika
Removed pika dependency.

2018-07-18 00:34 UTC, ipeternella commented on setup.cfg
> +max-line-length = 119
Removed this unnecessary change.

2018-07-18 00:34 UTC, ipeternella commented on tests/test_rabbitmq.py
> +    unittest.main()
Removed from the tests.

2018-07-18 00:35 UTC, ipeternella commented
Hello @codingjoe!

Thanks for the code review. I have implemented the requested changes. Please, could you take another look to see if it is acceptable now? Should you have any comments or new requests, please do so.

Thanks a lot!

2018-07-23 14:46 UTC, codingjoe requested changes
Almost there! Just some small changes and this is ready to roll. Thanks 👍

2018-07-23 14:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +            logger.info("Got %s as the broker_url. Connecting to rabbit...")
Argument for `%s` is missing

2018-07-23 14:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +            logger.info("Got %s as the broker_url. Connecting to rabbit...")
please use debug level here

2018-07-23 14:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +            logger.info("Openning a channel to RabbitMQ...")
same here, debug please

2018-07-23 14:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +            conn.close()
is there a context manager you could use? Even if something fails the connection should be closed

2018-07-23 14:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +        try:
There is too much happening in the try block. Please be more narrow, where you expect the exception to occour.

2018-07-23 14:46 UTC, codingjoe commented on health_check/contrib/rabbitmq/backends.py
> +        logger.info("Checking for a broker_url on django settings...")
debug please

2018-07-23 14:46 UTC, codingjoe commented on tests/test_rabbitmq.py
> +class TestRabbitMQHealthCheck(unittest.TestCase):
Again, we don't use `UnitTest` but `pytest`. Please just use a call and switch the assert to simple `assert` instead of `self.assertEqual` and co

2018-07-24 02:30 UTC, IgooorGP commented
Hey there @codingjoe ! Thanks again for the review. I have changed the code to use the kombu connection as a context to release opened resources. Also, I decided to use the connect method of the kombu library for the healthcheck because it is easier to understand, produces the same result as before and solves the problem with too many statements in the try/except blocks. Oh, of course, I have changed the tests as well. Please, could you review the code again to make sure everything's all right?

Thanks a lot!

2018-07-30 11:43 UTC, merged

2018-08-05 09:16 UTC, codingjoe commented
Released in [3.7.0](https://github.com/KristianOellegaard/django-health-check/releases/tag/3.7.0)