Adds 'app_name' to urlconf
codingjoe/django-health-check pull request #211
Opened 2019-01-24 13:09 UTC by sobolevn

When using you app like so:

```python
from health_check import urls as health_urls

```

Without this property I am getting this warning:

```
server/urls.py:32
  /Users/sobolev/Desktop/test_project/server/urls.py:32: RemovedInDjango20Warning: Specifying a namespace in django.conf.urls.include() without providing an app_name is deprecated. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
    url(r'^health/', include(health_urls, namespace='health')),

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

2019-02-02 10:36 UTC, codingjoe approved these changes

2019-02-02 10:38 UTC, codingjoe requested changes
Good catch @sobolevn. Would you mind adding the fixing the tests too? They are missing the namespace. Thanks for the contribution!

2019-02-03 09:47 UTC, sobolevn commented
I have also limited the version of `pytest` because of this error:

```
Traceback (most recent call last):
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/manager.py", line 268, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 4.2.0 (/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages), Requirement.parse('pytest!=4.2.0,>=3.6'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pytest.py", line 89, in <module>
    raise SystemExit(pytest.main())
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/_pytest/config/__init__.py", line 652, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/_pytest/config/__init__.py", line 838, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/_pytest/config/__init__.py", line 784, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages/pluggy/manager.py", line 274, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'django' could not be loaded: (pytest 4.2.0 (/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/lib/python3.6/site-packages), Requirement.parse('pytest!=4.2.0,>=3.6'))!
Coverage.py warning: No data was collected. (no-data-collected)
ERROR: InvocationError for command '/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/bin/coverage run --source=health_check -m pytest --basetemp=/Users/sobolev/Documents/github/django-health-check/.tox/py36-dj111/tmp --ignore=.tox' (exited with code 1)
```

2019-02-03 09:56 UTC, sobolevn commented
I have also silenced `flake8` to ignore : 
```python
from django.utils.translation import ugettext_lazy as _  # noqa: N812
```

2019-02-04 08:00 UTC, codingjoe approved these changes

2019-02-04 08:00 UTC, merged

2019-02-04 08:01 UTC, codingjoe commented
Released in [3.9.0](https://github.com/KristianOellegaard/django-health-check/releases/tag/3.9.0)