AppConfigs
codingjoe/django-health-check pull request #55
Opened 2016-09-26 19:40 UTC by astronouth7303

Closes #53.

Adds support for the use of explicit `AppConfig` references in `INSTALLED_APPS`.

2016-09-26 22:44 UTC, codingjoe commented
@astronouth7303 thanks for the contribution. It seems like the installation will fail if Django is not installed. Would you mind fixing that?

2016-09-26 22:47 UTC, astronouth7303 commented
... A project called `django-health-check`, only documents how to install on Django, is divided into Django-structured packages, and the majority of tests are Django specific, can be used by other frameworks?

2016-09-26 23:04 UTC, codingjoe commented
No Django sure is a dependency, that's not the issue. Your patch brakes `pip install` check out the travis output and you'll see what I mean.

2016-09-26 23:28 UTC, astronouth7303 commented
Ok, taken care of.

2016-10-04 19:05 UTC, codingjoe requested changes
Can you do me a favor and drop the commit that adds the migration, since this is already on master?
Let me know if you need help with that.

2016-10-04 19:41 UTC, astronouth7303 commented
This is why I don't use rebase or squash. It should be the same commit, but for some reason it's not.

2016-10-04 19:50 UTC, astronouth7303 commented
Ok, rebased.

2016-10-05 06:39 UTC, codingjoe approved these changes

2016-10-05 06:40 UTC, merged

2016-10-05 06:41 UTC, codingjoe commented
Released in 1.2.0