Added support for a JSON health endpoint
codingjoe/django-health-check pull request #72
Opened 2016-12-23 09:49 UTC by aleksihakli

Rebased #31 on top of the current master to get it finally merged.

2016-12-29 11:51 UTC, codingjoe requested changes
In general I like the idea.
I don't know if it's not better to use literals instead of integers in the JSON.

Besides that, you really should add some documentation here.

2016-12-29 11:51 UTC, codingjoe commented on health_check/urls.py
> +    url(r'^json/?$', json_view, name='health_check_json_view')
What do you think of not add a separate path but making the view header sensitive? You could request the response to be a json.
```
Accept: application/json
```

2016-12-29 11:51 UTC, codingjoe commented on health_check/backends/base.py
> +HEALTH_CHECK_JSON_STATUS_TYPE_TRANSLATOR = {
This could be an enum.

2016-12-29 11:51 UTC, codingjoe commented on tests/test_views.py
> +    from django.core.urlresolvers import reverse
No need to add support for any version prior to 1.8

2016-12-29 12:26 UTC, aleksihakli commented on health_check/urls.py
> +    url(r'^json/?$', json_view, name='health_check_json_view')
That's a good idea. I'll just add a different view per Accept header and add some documentation :)

2016-12-30 12:05 UTC, aleksihakli commented on health_check/backends/base.py
> +HEALTH_CHECK_JSON_STATUS_TYPE_TRANSLATOR = {
Should we refactor the original `HEALTH_CHECK_STATUS_TYPE_TRANSLATOR` as well, then? The current implementation uses the same logic for both; look up pretty response status based on the status code returned by the backend.

2016-12-30 14:29 UTC, aleksihakli commented
@codingjoe I refactored the view to return the status with the `Accept: application/json` header and added tests for the JSON output. I'll rebase the commit chain on top of the 2.0 rewrite later to keep the old attributions here.

2017-01-09 13:24 UTC, aleksihakli commented
Up-to-date PR in #80.

2017-01-09 13:24 UTC, closed without merging