Added support for a JSON health endpoint (rebased)
codingjoe/django-health-check pull request #80
Opened 2017-01-09 13:24 UTC by aleksihakli

Added support for JSON based health checks with tests on top of the current master branch.

2017-01-09 13:32 UTC, aleksihakli commented
@codingjoe I added support for the JSON responses based on the `Accept` header.

I don't know if a CBV is the best option for status rendering as we might want to customize the endpoint and add support for multiple different types of medias such as YAML etc. in the long run. Should we just use FBVs in the endpoint?

2017-01-10 08:05 UTC, aleksihakli commented
@codingjoe I think this is ready work-wise and good for merging from my part if it looks good to you.

2017-01-10 16:35 UTC, codingjoe requested changes
@aleksihakli I like it, just one tiny comment.
Oh and please add documentation 😉

2017-01-10 16:35 UTC, codingjoe commented on health_check/views.py
> +                {str(p.identifier()): str(p.pretty_status()) for p in plugins},
I would put this part into a different method. That way users can overwrite the structure of the dict that gets serialised into a JSON

2017-01-11 15:33 UTC, aleksihakli commented
@codingjoe I refactored the JSON endpoint so that it can be customized easily and added docs about the JSON output and customization to README.

2017-01-12 14:09 UTC, merged

2017-01-12 14:11 UTC, codingjoe commented
Released in 2.2.0