Send timezone-aware datetime for task expiry
codingjoe/django-health-check pull request #97
Opened 2017-02-07 20:23 UTC by crgwbr

Needed because this task would consistently fail if Django is set to a
later-than-UTC timezone, due to celery thinking the task expired the instant
it's sent.

2017-02-08 08:35 UTC, codingjoe requested changes
Hi @crgwbr thanks for the PR. Good catch!
I left you one little comment. Let me know your opinion. I'll review and merge this asap.

2017-02-08 08:35 UTC, codingjoe commented on health_check/contrib/celery/backends.py
> +                expires=datetime.now(tz=timezone.utc) + timedelta(seconds=timeout)
Why not use: `django.utils.timezone.now()`?

2017-02-09 16:15 UTC, crgwbr commented
@codingjoe Done!

2017-02-14 18:28 UTC, crgwbr commented
@codingjoe Bump. Any chance this can get merged and released soon?

2017-02-14 20:40 UTC, codingjoe approved these changes

2017-02-14 20:40 UTC, merged

2017-02-14 20:42 UTC, codingjoe commented
@crgwbr thanks and sorry for the delay.

Released in 2.2.2

2017-02-15 14:00 UTC, crgwbr commented
👍 Thanks!